- name: install and start nginx
  hosts: node
  become: yes
  tasks:
  - name: install nginx
    package: #ansible.builtin.package
      name: nginx
      state: present
  - name: start nginx
    service:
      name: nginx
      state: started # == systemctl start nginx
      enabled: yes # == systemctl enable nginx
