- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: Linux, Shell, Ansible, Terraform
    tagMap:
      name: Ansible
      project: roboshop
      environment: dev
    full_name: Purna Chand 
    ip_address_1: 1000.890.398.7898
    ip_address_2: 172.76.67.69
    tagsList: [
      {
        "key": "name",
        "value": "Ansible"        
      },
      {
        "key": "project",
        "value": "roboshop"
      },
      {
        "key": "environment",
        "value": "dev"
      }
    ]
  tasks:
  - name: print the string as list
    debug:
      msg:  "Topics are: {{ topics | split (',') }}"
  
  - name: set default value
    debug:
      msg: "Hi {{ GREETING | default ('Good Morning') }}"

  - name: convert map to list
    debug:
      msg: "{{ tagMap | dict2items }}"
  - name: convert list to map
    debug:
      msg: "{{ tagsList | items2dict }}"
  - name: convert to uppercase
    debug:
      msg: "{{ full_name | upper }}"
  - name: convert to lowercase
    debug:
      msg: "{{ full_name | lower }}"
  - name: check ipv4 ip_address_1
    debug:
      msg: "{{ ip_address_1 | ansible.utils.ipv4 }}"
    # ansible.utils.ipv4 require netaddr package, use pip3 install netaddr command to install the package
  - name: check ipv4 ip_address_2
    debug:
      msg: "{{ ip_address_2 | ansible.utils.ipv4 }}"


