[frontend]
172.31.39.189

; [catalogue]
; 172.31.39.190

; [user]
; 172.31.39.191

; [cart]
; 172.31.39.192

; ; group of groups
; [roboshop:children]
; frontend
; catalogue
; user
; cart

[localhost]
localhost